### ISSUE TITLE
Password will not change

### ISSUE THREAD

**Issue by anoopk350** [DennisSkov/WHMCSPasswordChange#1]
set password button not working.

**Comment by DennisSkov** [comment]
Which version of WHMCS are you using?
Open the network tab in the developer console, click the "Set Password" button and check what the response is for the request.
Make sure you've configured access to the module for you admin role.

**Comment by anoopk350** [comment]
whmcs version: Version: 8.3.1. granted all access to all users. still its not working

**Comment by DennisSkov** [comment]
Open the network tab in the developer console, click the "Set Password" button and check what the response is for the request.

**Comment by anoopk350** [comment]
its status is 500. Internal Server Error

**Comment by DennisSkov** [comment]
Enabling "Display Errors" in WHMCS > System Settings > General Settings > Other. Then check the response - you should see an error message.

**Comment by anoopk350** [comment]
No error throwing.

https://prnt.sc/q3sAkVCPARAu

**Comment by DennisSkov** [comment]
You need to check the response to the request in the "Network" tab as mentioned before.

**Comment by anoopk350** [comment]
on the module its throwing 500 Error

https://prnt.sc/Zc2-fW_zUTuJ

**Comment by DennisSkov** [comment]
Yes, that I already know. Either check your error log or check the response from the request.
See this: https://i.imgur.com/vI4wt7D.gif

The response will be much different since it's a 500 error. If you enabled error display, you should be able to see the exact error, though.
