### ISSUE TITLE
Module does not appear in "Addon Modules"

### ISSUE THREAD

**Issue by jawadshafiq** [DennisSkov/WHMCSPasswordChange#2]
Hi, I am using WHMCS 8.7.3.

I downloaded the module zip file from "https://github.com/DennisSkov/WHMCSPasswordChange/archive/refs/heads/master.zip" and unzipped the folder to "/whmcs/modules/addons" on my server. but the addon does NOT appear in WHMCS in "Admin > System Settings > Addon Modules".....

please help....
Jawad

**Comment by DennisSkov** [comment]
Hi.

Do you see a folder named "PasswordChange" inside of the modules folder?
Just to be clear: `/whmcs/modules/addons` is your WHMCS path. It's most likely `/home/username/public_html/modules/addons` - not just `/whmcs/`.

**Comment by jawadshafiq** [comment]
> Hi.
> 
> Do you see a folder named "PasswordChange" inside of the modules folder? Just to be clear: `/whmcs/modules/addons` is your WHMCS path. It's most likely `/home/username/public_html/modules/addons` - not just `/whmcs/`.


Do you see a folder named "PasswordChange" inside of the modules folder?
YES

The path is "public_html/main/modules/addons"

**Comment by DennisSkov** [comment]
Is there a file called `PasswordChange.php` directly  in `public_html/main/modules/addons/PasswordChange`?
What version of WHMCS are you using?

**Comment by jawadshafiq** [comment]
Is there a file called `PasswordChange.php` directly in `public_html/main/modules/addons/PasswordChange`?
YES

What version of WHMCS are you using?
WHMCS 8.7.3

**Comment by DennisSkov** [comment]
That makes no sense to me. I've just checked and it works just fine for me.
Are you sure the files are readable by the web server?

**Comment by jawadshafiq** [comment]
> That makes no sense to me. I've just checked and it works just fine for me. Are you sure the files are readable by the web server?

Fixed........ was an issue wit the hosting server, fixed by their help...
thank you for your help!!!

Plugin works great on WHMCS 8.7.3

**Comment by jawadshafiq** [comment]
Done
