### ISSUE TITLE
Stopped working on Version: 8.8.0

### ISSUE THREAD

**Issue by mahmoud1973** [DennisSkov/WHMCSPasswordChange#3]
The module stopped working after upgrading to Version: 8.8.0.

No error messages 

Please fix

Thank you!

**Comment by DennisSkov** [comment]
I've tested on v8.8.0 and I can change the password for the user just fine.
Are you getting the green confirmation notification at the bottom right?

**Comment by mahmoud1973** [comment]
> I've tested on v8.8.0 and I can change the password for the user just fine. Are you getting the green confirmation notification at the bottom right?

Thanks for the answer. I tried it once again and it's working good. Maybe I had a local issue.

Thanks for your help and confirming it's working with latest version. Keep up the good work!

Have a nice day.
